---
# @Author Victor Kritakis


- hosts: all
  vars_prompt:
  
  - name: pam_user
    prompt: "Please enter the name of the user you wish to add"
    private: no

  - name: user_pass
    prompt: "Please enter a password for this user "
    private: no  

  tasks: 
  # create new user
   - user: 
        name: '{{ pam_user}}'
        password: '{{user_pass}}'
        state: present
